# Generated by Django 6.0.3 on 2026-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdvisor',
            fields=[
                ('advisor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('class_id', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'advisors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAssignmentDefinition',
            fields=[
                ('assignment_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=15)),
                ('semester', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=120)),
                ('assigned_week', models.IntegerField()),
                ('due_week', models.IntegerField()),
                ('max_marks', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'assignment_definitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=10)),
                ('class_id', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('submission_date', models.DateTimeField(null=True)),
                ('latency_hours', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quality_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('plagiarism_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'assignment_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAttendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=10)),
                ('class_id', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=15)),
                ('semester', models.IntegerField()),
                ('week', models.IntegerField()),
                ('week_date', models.DateField()),
                ('lectures_held', models.IntegerField(default=3)),
                ('present', models.IntegerField(null=True)),
                ('absent', models.IntegerField(null=True)),
                ('late', models.IntegerField(null=True)),
                ('attendance_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientBookBorrow',
            fields=[
                ('borrow_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=10)),
                ('class_id', models.CharField(max_length=20)),
                ('semester', models.IntegerField(null=True)),
                ('book_title', models.CharField(max_length=120, null=True)),
                ('borrow_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('borrow_week', models.IntegerField(null=True)),
                ('return_week', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'book_borrows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientClass',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('year_of_study', models.IntegerField()),
                ('section', models.CharField(default='A', max_length=5)),
                ('branch', models.CharField(default='CSE', max_length=20)),
                ('batch_start_year', models.IntegerField(null=True)),
                ('total_students', models.IntegerField(null=True)),
                ('odd_sem', models.IntegerField(null=True)),
                ('even_sem', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientClassSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=15)),
                ('teacher_name', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'class_subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientExamResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_id', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=10)),
                ('class_id', models.CharField(max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max_marks', models.IntegerField(null=True)),
                ('score_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pass_fail', models.CharField(max_length=1, null=True)),
                ('grade', models.CharField(max_length=5, null=True)),
                ('result_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'exam_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientExamSchedule',
            fields=[
                ('schedule_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=20)),
                ('semester', models.IntegerField(null=True)),
                ('subject_id', models.CharField(max_length=15)),
                ('exam_type', models.CharField(max_length=15)),
                ('scheduled_week', models.IntegerField()),
                ('exam_date', models.DateField(null=True)),
                ('max_marks', models.IntegerField(default=50)),
                ('duration_mins', models.IntegerField(default=120)),
            ],
            options={
                'db_table': 'exam_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLibraryVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=10)),
                ('class_id', models.CharField(max_length=20)),
                ('semester', models.IntegerField(null=True)),
                ('week', models.IntegerField()),
                ('week_date', models.DateField(null=True)),
                ('physical_visits', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'library_visits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientQuizDefinition',
            fields=[
                ('quiz_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=15)),
                ('semester', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('scheduled_week', models.IntegerField()),
                ('quiz_date', models.DateField(null=True)),
                ('max_marks', models.IntegerField(default=10)),
                ('duration_mins', models.IntegerField(default=20)),
            ],
            options={
                'db_table': 'quiz_definitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientQuizSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz_id', models.CharField(max_length=15)),
                ('student_id', models.CharField(max_length=10)),
                ('class_id', models.CharField(max_length=20)),
                ('attempted', models.BooleanField(default=False)),
                ('attempt_date', models.DateTimeField(null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'quiz_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientSimState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('current_week', models.IntegerField()),
                ('sim_year', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sim_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientStudent',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=20)),
                ('advisor_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=80)),
                ('roll_number', models.IntegerField()),
                ('gender', models.CharField(max_length=1, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('parent_email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('archetype', models.CharField(default='consistent_avg', max_length=30)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientSubject',
            fields=[
                ('subject_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=80)),
                ('semester', models.IntegerField()),
                ('credits', models.IntegerField(default=4)),
                ('difficulty', models.CharField(default='Medium', max_length=10)),
                ('subject_type', models.CharField(default='Core', max_length=20)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='weekly_flags',
            new_name='weekly_flag_class_i_4e9756_idx',
            old_name='idx_wf_class_sem_week',
        ),
        migrations.RenameIndex(
            model_name='weekly_flags',
            new_name='weekly_flag_student_7110e5_idx',
            old_name='idx_wf_student',
        ),
        migrations.RenameIndex(
            model_name='weekly_metrics',
            new_name='weekly_metr_class_i_cc4152_idx',
            old_name='idx_wm_class_sem_week',
        ),
        migrations.RenameIndex(
            model_name='weekly_metrics',
            new_name='weekly_metr_student_976802_idx',
            old_name='idx_wm_student',
        ),
        migrations.AlterField(
            model_name='subject_difficulty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
